### ISSUE TITLE
Fatal Error is_main_query

### ISSUE THREAD

**Issue by natostanco** [10up/ElasticPress-Admin#11] opened 2015-05-14 10:28 UTC
```
nFatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function is_main_query() on a non-object (NULL)' in /.../wp-includes/query.php:730\nStack trace:\n#0 /.../plugins/ElasticPress-Admin/includes/class-epa-integration.php(41):
```

**Comment by AaronHolbrook** [comment] 2016-03-22 14:59
Duplicate of #14

**Closed by AaronHolbrook** 2016-03-22 14:59 UTC
